include:
  - board: nice_nano_v2//zmk
    shield: tuball4_right

  - board: nice_nano_v2//zmk
    shield: tuball4_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: nice_nano_v2//zmk
    shield: settings_reset
